import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link';

import { JetBrains_Mono } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })
const jetbrains_mono = JetBrains_Mono({
  subsets: ['latin'],
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <div className={jetbrains_mono.className}>
         
        </div>
      </body>
    </html>
  )
}
